/*
 * Copyright 2026-present the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.gatool.tests.skeleton;

import java.nio.charset.StandardCharsets;
import java.util.List;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.context.SpringBootTest.WebEnvironment;
import org.springframework.boot.test.system.CapturedOutput;
import org.springframework.boot.test.system.OutputCaptureExtension;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import org.springframework.web.client.RestClient;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * The scopes an operation file lists, enforced at the endpoint: a call needs the baseline
 * and the tool's own, every challenge names what to ask for, and a 403 says what the
 * token held and lacked.
 */
@ExtendWith(OutputCaptureExtension.class)
@SpringBootTest(webEnvironment = WebEnvironment.RANDOM_PORT,
		properties = { "spring.ai.mcp.server.protocol=STATELESS",
				"gatool.api.schema.location=classpath:io/gatool/fixtures/movies/movies.graphqls",
				"gatool.mcp.operations.locations=classpath:gatool/scoped/",
				"spring.security.oauth2.resourceserver.jwt.audiences=gatool-skeleton",
				"gatool.mcp.security.baseline-scopes=mcp:tools" })
class McpToolScopesOverHttpTests {

	private static final String AUDIENCE = "gatool-skeleton";

	private static final String TOOLS_LIST = "{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"tools/list\",\"params\":{}}";

	@LocalServerPort
	private int port;

	@DynamicPropertySource
	static void servers(DynamicPropertyRegistry registry) {
		registry.add("spring.security.oauth2.resourceserver.jwt.issuer-uri", () -> LocalIssuer.get().url());
		registry.add("gatool.api.url", MoviesApiServer::graphQlUrl);
	}

	@Test
	void callTool_withTheBaselineAlone_shouldAnswer403NamingTheToolsScopesAndWhatTheTokenHeld(CapturedOutput output) {
		ResponseEntity<String> response = post(token("mcp:tools"), callBody("topRatedMovies"));

		assertThat(response.getStatusCode()).isEqualTo(HttpStatus.FORBIDDEN);
		// The scope parameter is what the client asks for next, and the description says
		// what the token had, limited to the scopes this server itself defines.
		assertThat(challenge(response)).contains("error=\"insufficient_scope\"")
			.contains("scope=\"mcp:tools movies:read\"")
			.contains("error_description=\"topRatedMovies needs mcp:tools movies:read. The token holds "
					+ "mcp:tools and lacks movies:read.\"")
			// The correlation id stays in the log, so two refusals of one caller for
			// one missing scope carry the same challenge and a client can compare them.
			.doesNotContain("Correlation id")
			.contains("resource_metadata=\"http://127.0.0.1:" + this.port
					+ "/.well-known/oauth-protected-resource/mcp\"");
		assertThat(output.getAll())
			.contains("GATool answered 403 insufficient_scope to a call of topRatedMovies: "
					+ "the token holds mcp:tools and lacks movies:read. Correlation id ")
			.contains("generated by GATool, because tracing is off");
	}

	@Test
	void callTool_withTheToolsScopes_shouldReachTheApi() {
		ResponseEntity<String> response = post(token("mcp:tools", "movies:read"), callBody("topRatedMovies"));

		assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);
		assertThat(response.getBody()).contains("Signal from Kepler");
	}

	@Test
	void callTool_withAScopeOutsideTheCall_shouldKeepItInTheScopeParameter() {
		// The token holds movies:detail from an earlier step-up and lacks movies:read,
		// so the challenge asks for what the call needs and keeps what the token had,
		// and a client that signs in again keeps everything it had.
		ResponseEntity<String> response = post(token("mcp:tools", "movies:detail"), callBody("topRatedMovies"));

		assertThat(response.getStatusCode()).isEqualTo(HttpStatus.FORBIDDEN);
		assertThat(challenge(response)).contains("scope=\"mcp:tools movies:read movies:detail\"")
			.contains("The token holds mcp:tools movies:detail and lacks movies:read.");
	}

	@Test
	void callTool_needingTwoScopesWithOneOfThem_shouldAnswer403NamingTheMissingOne() {
		ResponseEntity<String> response = post(token("mcp:tools", "movies:read"),
				"{\"jsonrpc\":\"2.0\",\"id\":2,\"method\":\"tools/call\",\"params\":{\"name\":\"movieByLookup\","
						+ "\"arguments\":{\"by\":{\"id\":\"movie-1\"}}}}");

		assertThat(response.getStatusCode()).isEqualTo(HttpStatus.FORBIDDEN);
		assertThat(challenge(response)).contains("scope=\"mcp:tools movies:read movies:detail\"")
			.contains("The token holds mcp:tools movies:read and lacks movies:detail.");
	}

	@Test
	void callTool_openToEveryCaller_shouldRunWithTheBaselineAlone() {
		ResponseEntity<String> response = post(token("mcp:tools"),
				"{\"jsonrpc\":\"2.0\",\"id\":2,\"method\":\"tools/call\",\"params\":{\"name\":\"searchMovies\","
						+ "\"arguments\":{\"text\":\"a\"}}}");

		assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);
		assertThat(response.getBody()).contains("\\\"__typename\\\":\\\"Movie\\\"");
	}

	@Test
	void callTool_thatDeclaresNoScopes_shouldRunWithTheBaselineAlone() {
		// A file without the argument needs the baseline alone, which is the rule
		// for a credential that keeps the caller's identity.
		ResponseEntity<String> response = post(token("mcp:tools"), callBody("moviesPage"));

		assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);
		assertThat(response.getBody()).contains("\"isError\":false");
	}

	@Test
	void callTool_withoutAToken_shouldAnswer401NamingTheBaselineAndTheToolsScopes() {
		ResponseEntity<String> response = post(null, callBody("topRatedMovies"));

		// The 401 already names the tool's scopes, so a client signing in for this call
		// asks for everything it will need.
		assertThat(response.getStatusCode()).isEqualTo(HttpStatus.UNAUTHORIZED);
		assertThat(challenge(response)).contains("scope=\"mcp:tools movies:read\"");
	}

	@Test
	void listTools_withoutAToken_shouldAnswer401NamingTheBaselineAlone() {
		ResponseEntity<String> response = post(null, TOOLS_LIST);

		assertThat(response.getStatusCode()).isEqualTo(HttpStatus.UNAUTHORIZED);
		assertThat(challenge(response)).contains("scope=\"mcp:tools\"");
	}

	@Test
	void callTool_namingAToolThisServerLacks_shouldPassSecurityAndLetTheServerAnswer() {
		// An unknown name needs the baseline alone, and the MCP server answers it the
		// way the protocol says, so the check keeps which tools exist to itself.
		ResponseEntity<String> response = post(token("mcp:tools"), callBody("nothingLikeThis"));

		assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);
		assertThat(response.getBody()).contains("Unknown tool");
	}

	@Test
	void callTool_bodyDeclaredInUtf16_shouldBeRefusedAheadOfTheScopeCheck() {
		// Read as UTF-8 the bytes lack a tool name, so the baseline alone would pass the
		// call, and the MCP server reading UTF-16 would run the scoped tool.
		ResponseEntity<String> response = RestClient.builder()
			.baseUrl("http://127.0.0.1:" + this.port)
			.build()
			.post()
			.uri("/mcp")
			.header(HttpHeaders.CONTENT_TYPE, "application/json; charset=UTF-16")
			.accept(MediaType.APPLICATION_JSON, MediaType.TEXT_EVENT_STREAM)
			.header("MCP-Protocol-Version", "2025-11-25")
			.headers((headers) -> headers.setBearerAuth(token("mcp:tools")))
			.body(callBody("topRatedMovies").getBytes(StandardCharsets.UTF_16))
			.exchange((request, reply) -> new ResponseEntity<>(reply.bodyTo(String.class), reply.getHeaders(),
					reply.getStatusCode()));

		assertThat(response.getStatusCode()).isEqualTo(HttpStatus.BAD_REQUEST);
		assertThat(response.getBody()).contains("UTF-16").doesNotContain("Signal from Kepler");
	}

	@Test
	void callTool_namingAToolWithHeaderCharactersInItsName_shouldBeRefusedAheadOfEveryChallenge(CapturedOutput output) {
		// The name could reach a challenge header and a log line, and a registered tool
		// cannot carry one like it, so the filter refuses the call ahead of the chain.
		ResponseEntity<String> response = post(token("mcp:tools"),
				callBody("topRatedMovies\\r\\nWWW-Authenticate: Basic realm=\\\"x\\\""));

		// The status is 200, because the Java client drops its session on a 400.
		assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);
		assertThat(response.getBody()).contains("-32602");
		assertThat(response.getHeaders().containsHeader(HttpHeaders.WWW_AUTHENTICATE)).isFalse();
		assertThat(output.getAll()).doesNotContain("Basic realm");
	}

	@Test
	void callTool_asMultipart_shouldBeRefusedAheadOfTheServer() {
		ResponseEntity<String> response = RestClient.builder()
			.baseUrl("http://127.0.0.1:" + this.port)
			.build()
			.post()
			.uri("/mcp")
			.header(HttpHeaders.CONTENT_TYPE, "multipart/form-data; boundary=x")
			.accept(MediaType.APPLICATION_JSON, MediaType.TEXT_EVENT_STREAM)
			.header("MCP-Protocol-Version", "2025-11-25")
			.headers((headers) -> headers.setBearerAuth(token("mcp:tools", "movies:read")))
			.body(callBody("topRatedMovies"))
			.exchange((request, reply) -> new ResponseEntity<>(reply.bodyTo(String.class), reply.getHeaders(),
					reply.getStatusCode()));

		assertThat(response.getStatusCode()).isEqualTo(HttpStatus.UNSUPPORTED_MEDIA_TYPE);
		assertThat(response.getBody()).contains("application/json");
	}

	@Test
	void post_aJsonRpcBatch_shouldBeRefusedWithInvalidRequest() {
		ResponseEntity<String> response = post(token("mcp:tools"), "[" + TOOLS_LIST + "]");

		assertThat(response.getStatusCode()).isEqualTo(HttpStatus.BAD_REQUEST);
		assertThat(response.getBody()).contains("-32600");
	}

	@Test
	void metadata_anonymousGet_shouldPublishTheBaselineScopesAlone() {
		ResponseEntity<String> response = RestClient.builder()
			.baseUrl("http://127.0.0.1:" + this.port)
			.build()
			.get()
			.uri("/.well-known/oauth-protected-resource/mcp")
			.retrieve()
			.toEntity(String.class);

		// The tools' own scopes arrive through step-up, so sign-in asks for the baseline.
		assertThat(response.getBody()).contains("\"scopes_supported\":[\"mcp:tools\"]");
	}

	private static String callBody(String tool) {
		return "{\"jsonrpc\":\"2.0\",\"id\":2,\"method\":\"tools/call\",\"params\":{\"name\":\"" + tool
				+ "\",\"arguments\":{\"first\":1}}}";
	}

	private static String token(String... scopes) {
		return LocalIssuer.get().token(AUDIENCE, List.of(scopes));
	}

	private ResponseEntity<String> post(String token, String body) {
		return RestClient.builder()
			.baseUrl("http://127.0.0.1:" + this.port)
			.build()
			.post()
			.uri("/mcp")
			.contentType(MediaType.APPLICATION_JSON)
			.accept(MediaType.APPLICATION_JSON, MediaType.TEXT_EVENT_STREAM)
			.header("MCP-Protocol-Version", "2025-11-25")
			.headers((headers) -> {
				if (token != null) {
					headers.setBearerAuth(token);
				}
			})
			.body(body)
			.exchange((request, reply) -> new ResponseEntity<>(reply.bodyTo(String.class), reply.getHeaders(),
					reply.getStatusCode()));
	}

	private static String challenge(ResponseEntity<String> response) {
		String header = response.getHeaders().getFirst(HttpHeaders.WWW_AUTHENTICATE);
		assertThat(header).isNotNull();
		return header;
	}

	@SpringBootApplication
	static class SkeletonApplication {

	}

}
